setup:
  runner: train_dpdm_base
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6029
  omp_n_threads: 8
data:
  path: data_dir
  specific_class: null
  img_num: null
  name: pretrain_mean_camelyon
  num_channels: 3
  resolution: 32
  n_classes: 2
  fid_stats: 
  - fid_dir
  one_hot: False
  dataloader_params:
    num_workers: 1
    pin_memory: True
  aug:
    random: True
    magnitude: 9
    num_ops: 2
model:
  ckpt: null
  denoiser_name: edm
  denoiser_network: song
  ema_rate: .999
  network:
    image_size: 32
    label_dim: 2
    num_in_channels: 3
    num_out_channels: 3
    attn_resolutions:
    - 16
    ch_mult: [1, 2, 2]
    num_res_blocks: 2
optim:
  optimizer: Adam
  params:
    lr: 3e-4
    weight_decay: 0.
sampler:
  type: ddim
  stochastic: False
  num_steps: 50
  tmin: 0.002
  tmax: 80.
  rho: 7.
  guid_scale: 0.
  snapshot_batch_size: 16
  fid_batch_size: 256
sampler_fid:
  type: edm
  s_churn: 50
  s_min: 0.025
  s_max: 50
  num_steps: 50
  tmin: .002
  tmax: 80.
  rho: 7.
  guid_scale: 0.
train:
  seed: 0
  batch_size: 64
  n_epochs: 300
  log_freq: 50
  snapshot_freq: 1000
  snapshot_threshold: 1
  save_freq: 100000
  save_threshold: 1
  fid_freq: 1000
  fid_samples: 5000
  final_fid_samples: 5000
  fid_threshold: 1
  gen: False
  nocond2cond: False
loss: 
  version: edm
  p_mean: -1.2
  p_std: 1.2
  n_noise_samples: 1
  n_classes: 2
dp:
  epsilon: infinite