setup:
  runner: train_dpdm_base
  n_gpus_per_node: 4
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6028
  omp_n_threads: 8
data:
  path: data_dir
  name: camelyon_32
  num_channels: 3
  resolution: 32
  n_classes: 2
  fid_stats: 
  - fid_dir
  one_hot: True
  attr: null
  dataloader_params:
    num_workers: 2
    pin_memory: True
  dataset_params:
    use_labels: True
  split: train
model:
  ckpt: model_dir
  denoiser_name: edm
  denoiser_network: song
  ema_rate: .999
  network:
    image_size: 32
    label_dim: 2
    num_in_channels: 3
    num_out_channels: 3
    attn_resolutions:
    - 16
    ch_mult: [1, 2, 2]
    num_res_blocks: 2
optim:
  optimizer: Adam
  params:
    lr: 3e-4
    weight_decay: 0.
sampler:
  type: ddim
  stochastic: False
  num_steps: 50
  tmin: .002
  tmax: 80.
  rho: 7.
  guid_scale: 0.
  snapshot_batch_size: 64
  fid_batch_size: 128
sampler_fid:
  type: edm
  s_churn: 50
  s_min: 0.005
  s_max: 50
  num_steps: 1000
  tmin: .002
  tmax: 80.
  rho: 7.
  guid_scale: 0.
sampler_acc:
  type: ddim
  stochastic: False
  num_steps: 50
  tmin: .002
  tmax: 80.
  rho: 7.
  guid_scale: 0.
  labels: 2
  batch_size: 6001
  sample_num: 60000
train:
  seed: 0
  batch_size: 2048
  n_epochs: 20
  log_freq: 100
  snapshot_freq: 10000
  snapshot_threshold: 1
  save_freq: 1000000
  save_threshold: 1
  fid_freq: 10000
  fid_samples: 5000
  final_fid_samples: 60000
  fid_threshold: 1
  gen: True
loss: 
  version: edm
  p_mean: -1.2
  p_std: 1.2
  n_noise_samples: 32
  n_classes: 2
dp:
  sdq: True
  privacy_history: [[10, 0.04, 250]]
  alpha_num: 0
  max_grad_norm: 1.0
  delta: 1e-6
  epsilon: 10.
  max_physical_batch_size: 2048
  n_splits: 32