setup:
  runner: train_dpdm_base
  n_gpus_per_node: 3
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6025
  omp_n_threads: 64
data:
  path: data_dir
  name: mnist_28
  num_channels: 1
  resolution: 28
  n_classes: 10
  fid_stats: 
  - ./data/mnist_train.npz
  one_hot: False
  dataloader_params:
    num_workers: 2
    pin_memory: True
  dataset_params:
    use_labels: True
model:
  ckpt: pretrain_mnist28_e1_mean_ch22_at14_n5_sig5_q0.1/checkpoints/final_checkpoint.pth
  denoiser_name: edm
  denoiser_network: song
  ema_rate: .999
  network:
    image_size: 28
    attn_resolutions:
    - 14
    ch_mult: [2, 2]
optim:
  optimizer: Adam
  params:
    lr: 3e-4
    weight_decay: 0.
sampler:
  type: ddim
  stochastic: False
  num_steps: 50
  tmin: .002
  tmax: 80.
  rho: 7.
  guid_scale: 0.
  snapshot_batch_size: 80
  fid_batch_size: 256
sampler_fid:
  type: edm
  s_churn: 100
  s_min: 0.05
  s_max: 50
  num_steps: 1000
  tmin: .002
  tmax: 80.
  rho: 7.
  guid_scale: 0.
sampler_acc:
  type: edm
  s_churn: 10
  s_min: 0.1
  s_max: 50
  num_steps: 1000
  tmin: .002
  tmax: 80.
  rho: 7.
  guid_scale: 0.
  labels: 10
  batch_size: 6001
  sample_num: 60000
train:
  seed: 0
  batch_size: 4096
  n_epochs: 150
  log_freq: 100
  snapshot_freq: 2000
  snapshot_threshold: 1
  save_freq: 100000
  save_threshold: 1
  fid_freq: 2000
  fid_samples: 5000
  final_fid_samples: 60000
  fid_threshold: 1
  gen: True
loss: 
  version: edm
  p_mean: -1.2
  p_std: 1.2
  n_noise_samples: 32
  n_classes: 10
dp:
  sdq: True
  privacy_history: [[5, 0.1, 5]]
  alpha_num: 0
  max_grad_norm: 1.0
  delta: 1e-5
  epsilon: 1.
  max_physical_batch_size: 8192
  n_splits: 32